# @package _global_

defaults:
  - cifar100

name: cifar100_id_${add_to_name}

timing_verbose: False

combined_total_per_class: 1000

training_loop:
  config:
    id_estimation: ${id_estimation}

id_estimation:
  layers: [conv1,conv2_x,conv3_x,conv4_x,conv5_x,avg_pool]
  combined_total_per_class: ${combined_total_per_class}
  num_per_class: 1000

  timing_verbose: ${timing_verbose}

  max_epochs: ${max_epochs}

  fraction: 0.9
  nres: 20

  estimate_id_every: 1
  estimate_initial_id: False
  estimate_data_id: True
  estimate_train_id: False
  estimate_class_id: False
  no_restrict: False

  do_steps: True # Is estimate_id_every in epochs or steps
  
  save_path: ${save_dir}/id_estimates.pkl

  dataloader:
    batch_size: 1024
    shuffle: False
    num_workers: ${num_workers}
